version: "3.7"

networks:
  training-network:
    driver: bridge

services:
  api.pokemon:
    container_name: training-api.pokemon.local
    build:
      context: backend/api.pokemon
      dockerfile: Dockerfile
    environment:
      - VHOST_HOSTNAME=api.pokemon.local
      - VHOST_DOCROOT=/var/www/api
    ports:
      - "19180:80"
      - "19143:443"
    volumes:
      - ./backend/api.pokemon/api:/var/www/api
      - ./backend/api.pokemon/src:/var/www/src
      - ./backend/api.pokemon/vendor:/var/www/vendor
    networks:
      - training-network
    links:
      - mongo.pokemon:dbcat

  front-end:
    container_name: training-vuejs
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - "8081:8080"
    networks:
      - training-network

  #############################
  # databases
  #############################
  mongo.pokemon:
    container_name: training-mongo.pokemon
    image: mongo:latest
    volumes:
      - ./backend/api.pokemon/data:/var/data
    working_dir: /var/data
    networks:
      - training-network
    ports:
      - 27018:27017